# Generated by Django 6.0.4 on 2026-04-19 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('region', models.CharField(default='All Regions', max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('ai', 'AI Chat'), ('expert', 'Expert Chat')], default='ai', max_length=10)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending', 'Pending')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Farmer'), ('assistant', 'AI'), ('expert', 'Expert')], default='user', max_length=15)),
                ('content', models.TextField()),
                ('language', models.CharField(default='ur', max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('item_type', models.CharField(choices=[('article', 'Article'), ('announcement', 'Announcement'), ('tip', 'Farming Tip')], default='article', max_length=20)),
                ('region', models.CharField(default='All Regions', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('crop_disease', 'Crop Disease'), ('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer'), ('market', 'Market Prices'), ('weather', 'Weather'), ('general', 'General')], default='general', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_chats', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expert'),
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('land_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('primary_crop', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('ur', 'Urdu'), ('pa', 'Punjabi'), ('en', 'English'), ('sd', 'Sindhi')], default='ur', max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ur', models.CharField(blank=True, help_text='Urdu title', max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('subsidy', 'Financial Subsidy'), ('equipment', 'Equipment / Machinery'), ('water', 'Water Management'), ('seeds', 'Seeds & Fertilizer'), ('solar', 'Solar / Energy'), ('organic', 'Organic Farming'), ('insurance', 'Crop Insurance'), ('training', 'Training & Education')], default='subsidy', max_length=20)),
                ('target_region', models.CharField(default='All Regions', max_length=200)),
                ('beneficiaries', models.PositiveIntegerField(default=0, help_text='Number of registered beneficiaries')),
                ('budget_pkr', models.BigIntegerField(blank=True, help_text='Total budget in PKR', null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Under Review'), ('draft', 'Draft'), ('expired', 'Expired')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('farm_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('full', 'Full Kit (Soil + DHT22)'), ('soil', 'Soil Only'), ('weather', 'Weather Station')], default='full', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_name_ur', models.CharField(blank=True, help_text='Urdu name e.g. گندم', max_length=100)),
                ('mandi_name', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('40kg', 'PKR / 40kg'), ('mound', 'PKR / Mound'), ('kg', 'PKR / kg'), ('ton', 'PKR / Ton')], default='40kg', max_length=10)),
                ('price_change', models.DecimalField(decimal_places=2, default=0, help_text='% change from yesterday. Positive = up, Negative = down.', max_digits=5)),
                ('status', models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('draft', 'Draft')], default='draft', max_length=15)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Rate',
                'ordering': ['-date_recorded', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.iotdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
