# Generated by Django 6.0.5 on 2026-05-21 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Content Item', 'verbose_name_plural': 'Content Items'},
        ),
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['-rating', '-joined_at'], 'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Farmer Profile', 'verbose_name_plural': 'Farmer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='governmentscheme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Government Scheme', 'verbose_name_plural': 'Government Schemes'},
        ),
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'ordering': ['-registered'], 'verbose_name': 'IoT Device', 'verbose_name_plural': 'IoT Devices'},
        ),
        migrations.AlterModelOptions(
            name='marketrate',
            options={'ordering': ['-date_recorded', '-updated_at'], 'verbose_name': 'Market Rate', 'verbose_name_plural': 'Market Rates'},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Sensor Reading', 'verbose_name_plural': 'Sensor Readings'},
        ),
        migrations.AlterModelOptions(
            name='weatheralert',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Weather Alert', 'verbose_name_plural': 'Weather Alerts'},
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='application_process',
            field=models.TextField(blank=True, help_text='How farmers can apply.'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='benefits',
            field=models.TextField(blank=True, help_text='Main benefits of the scheme.'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Who can apply for this scheme?'),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='official_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='required_documents',
            field=models.TextField(blank=True, help_text='CNIC, land record, application form, etc.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='language',
            field=models.CharField(db_index=True, default='ur', max_length=5),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Farmer'), ('assistant', 'AI'), ('expert', 'Expert'), ('system', 'System')], db_index=True, default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='farmer',
            field=models.ForeignKey(blank=True, help_text='Can be empty for public/mobile guest chatbot messages.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='started_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending', 'Pending')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='item_type',
            field=models.CharField(choices=[('article', 'Article'), ('announcement', 'Announcement'), ('tip', 'Farming Tip')], db_index=True, default='article', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='region',
            field=models.CharField(db_index=True, default='All Regions', max_length=200),
        ),
        migrations.AlterField(
            model_name='expert',
            name='specialization',
            field=models.CharField(choices=[('crop_disease', 'Crop Disease'), ('irrigation', 'Irrigation'), ('fertilizer', 'Fertilizer'), ('market', 'Market Prices'), ('weather', 'Weather'), ('general', 'General')], db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='expert',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='primary_crop',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='category',
            field=models.CharField(choices=[('subsidy', 'Financial Subsidy'), ('equipment', 'Equipment / Machinery'), ('water', 'Water Management'), ('seeds', 'Seeds & Fertilizer'), ('solar', 'Solar / Energy'), ('organic', 'Organic Farming'), ('insurance', 'Crop Insurance'), ('training', 'Training & Education')], db_index=True, default='subsidy', max_length=20),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('review', 'Under Review'), ('draft', 'Draft'), ('expired', 'Expired')], db_index=True, default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='target_region',
            field=models.CharField(db_index=True, default='All Regions', max_length=200),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='last_ping',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='crop_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='date_recorded',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='mandi_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% change from yesterday. Positive = up, negative = down.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='region',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='marketrate',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('draft', 'Draft')], db_index=True, default='draft', max_length=15),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='region',
            field=models.CharField(db_index=True, default='All Regions', max_length=200),
        ),
        migrations.AlterField(
            model_name='weatheralert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=15),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['status', 'category'], name='core_govern_status_1d70cd_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['target_region', 'status'], name='core_govern_target__b25c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='governmentscheme',
            index=models.Index(fields=['deadline'], name='core_govern_deadlin_9cc9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='marketrate',
            index=models.Index(fields=['crop_name', 'region'], name='core_market_crop_na_00d57f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketrate',
            index=models.Index(fields=['mandi_name', 'date_recorded'], name='core_market_mandi_n_5ecab0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketrate',
            index=models.Index(fields=['status', 'date_recorded'], name='core_market_status_293ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'timestamp'], name='core_sensor_device__30fb63_idx'),
        ),
    ]
